apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: hdx-portal-admin-frontend
  namespace: kubeflow
spec:
  rules:
  - {}
  selector:
    matchLabels:
      app: hdx-portal-admin-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: hdx-portal-admin-frontend
  namespace: kubeflow
spec:
  selector:
    app: hdx-portal-admin-frontend
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdx-portal-admin-frontend
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      app: hdx-portal-admin-frontend
  template:
    metadata:
      labels:
        app: hdx-portal-admin-frontend
    spec:
      containers:
      - image: "{{.Values.nexusDomain}}/docker-local/matilda-frontend:{{.Values.adminFrontendTag}}"
        imagePullPolicy: Always
        name: hdx-portal-admin-frontend
        ports:
        - containerPort: 8080
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: nexuscred
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

