apiVersion: v1
kind: Service
metadata:
  name: hdx-portal-project-exporter-svc
  namespace: kubeflow
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hdx-portal-project-exporter
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdx-portal-project-exporter
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      app: hdx-portal-project-exporter
  template:
    metadata:
      labels:
        app: hdx-portal-project-exporter
    spec:
      containers:
      - env:
        - name: DATABASE_HOST
          value: postgresql.database.svc.cluster.local
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USER
          value: postgres
        - name: DATABASE_PASSWORD
          value: megazone00!
        - name: DATABASE_NAME
          value: postgres
        image: {{.Values.nexusDomain}}/docker-local/project-exporter:latest
        imagePullPolicy: Always
        name: hdx-portal-project-exporter
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 2000Mi
          requests:
            cpu: 10m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /project
          name: project-pv
          subPath: public
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: nexuscred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: project-pv
        persistentVolumeClaim:
          claimName: project-pvc
---

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: hdx-portal-project-exporter
  namespace: kubeflow
spec:
  rules:
  - {}
  selector:
    matchLabels:
      app: hdx-portal-project-exporter
